/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.MenuComponent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import utils.DB;

/**
 *
 * @author hp1
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
this.setTitle(" MY STORE CONNECTION ✌");
             this.setLocationRelativeTo(null);
             
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formnamelabel = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        pwdlabel = new javax.swing.JLabel();
        PwdField = new javax.swing.JPasswordField();
        connexionbutton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        formnamelabel.setFont(new java.awt.Font("AR CENA", 0, 24)); // NOI18N
        formnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        formnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formnamelabel.setLabelFor(formnamelabel);
        formnamelabel.setText("FORMULAIRE DE CONNEXION");

        idlabel.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        idlabel.setForeground(new java.awt.Color(255, 255, 255));
        idlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idlabel.setText("IDENTIFIANT");

        IdField.setText("a");

        pwdlabel.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        pwdlabel.setForeground(new java.awt.Color(255, 255, 255));
        pwdlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pwdlabel.setText("MOT DE PASSE");
        pwdlabel.setMaximumSize(new java.awt.Dimension(57, 15));
        pwdlabel.setMinimumSize(new java.awt.Dimension(57, 15));

        PwdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PwdFieldKeyPressed(evt);
            }
        });

        connexionbutton.setFont(new java.awt.Font("AR CENA", 1, 18)); // NOI18N
        connexionbutton.setText("CONNEXION");
        connexionbutton.setBorder(new javax.swing.border.SoftBevelBorder(0));
        connexionbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connexionbuttonMouseClicked(evt);
            }
        });
        connexionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionbuttonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(connexionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(formnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(connexionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connexionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionbuttonActionPerformed

Ids();
    }//GEN-LAST:event_connexionbuttonActionPerformed

    private void connexionbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connexionbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_connexionbuttonMouseClicked

    private void PwdFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PwdFieldKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Ids(); 
         }
    }//GEN-LAST:event_PwdFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

   public void Ids(){
            
            Statement stmt = DB.getStatement();
            String sql = "select * from users  where users.Identifiant ='" +IdField.getText()+"' and mot_de_passe = '" +PwdField.getText()+"'";
            try{
            ResultSet rs = stmt.executeQuery(sql); 
                if(rs.next()){
                    String role = rs.getString("role");
                     if("boss".equals(role)){
                    VenteFrame Vente = new VenteFrame();
                   Vente.setVisible(true);
                   this.setVisible(false);
                     }
                     if("vendeur".equals(role)){
                   vente2Frame Vente2 = new vente2Frame();
         Vente2.setVisible(true);
         this.setVisible(false); 
                }
                   if("".equals(role)){
                     JOptionPane.showMessageDialog(null, "Utilisateur reconnu mais pas de role défini🤔");  
                   } 
                }
                else {
                  JOptionPane.showMessageDialog(null, "UTILISATEUR NON RECONNU 🤔"); 
                }
            }catch (Exception exp){
                exp.printStackTrace();
               // JOptionPane.showMessageDialog(null, "UTILISATEUR NON RECONNU 🤔 ");
              }
          }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdField;
    private javax.swing.JPasswordField PwdField;
    private javax.swing.JButton connexionbutton;
    private javax.swing.JLabel formnamelabel;
    private javax.swing.JLabel idlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pwdlabel;
    // End of variables declaration//GEN-END:variables
}
