/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.print.PrinterException;
import static java.lang.Thread.sleep;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utils.DB;

/**
 *
 * @author hp1
 */
public class vente2Frame extends javax.swing.JFrame {

    /**
     * Creates new form vente2Frame
     */
    public vente2Frame() {
                this.clock = new Thread(){
            @Override
            public void run(){
                while (true){
                    SimpleDateFormat df = new SimpleDateFormat(("dd MM yyyy -") + ("- HH:mm:ss"));
                    DateLabel.setText(df.format(Calendar.getInstance().getTime()));
                    try{
                        sleep(500);
                    }catch (InterruptedException ie){
                    }
                }
            }
        };
                
        initComponents();
        RemplirTableauProduit();
        clock.start();
                     this.setLocationRelativeTo(null);
             this.setResizable(true);
             this.setTitle(" MY STORE (USER)✌");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        DateLabel = new javax.swing.JLabel();
        VentesTab = new javax.swing.JPanel();
        ChoixProduitTabVente2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FactureScroll1 = new javax.swing.JScrollPane();
        FactureTable = new javax.swing.JTable();
        TotalLabel = new javax.swing.JLabel();
        TotalField = new javax.swing.JTextField();
        FactureName = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        NpLabel = new javax.swing.JLabel();
        NpField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ImpressionBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProduitsTable = new javax.swing.JTable();
        SearchBtn = new javax.swing.JButton();
        SearchBar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        DateLabel.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateLabelMouseClicked(evt);
            }
        });

        VentesTab.setBackground(java.awt.SystemColor.activeCaption);

        ChoixProduitTabVente2.setBackground(java.awt.SystemColor.activeCaption);

        jLabel4.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LISTE DES PRODUITS");

        javax.swing.GroupLayout ChoixProduitTabVente2Layout = new javax.swing.GroupLayout(ChoixProduitTabVente2);
        ChoixProduitTabVente2.setLayout(ChoixProduitTabVente2Layout);
        ChoixProduitTabVente2Layout.setHorizontalGroup(
            ChoixProduitTabVente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoixProduitTabVente2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ChoixProduitTabVente2Layout.setVerticalGroup(
            ChoixProduitTabVente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChoixProduitTabVente2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FactureTable.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        FactureTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "code", "Designation", "Quantité", "Prix unitaire"
            }
        ));
        FactureTable.setColumnSelectionAllowed(true);
        FactureTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FactureTableMouseClicked(evt);
            }
        });
        FactureScroll1.setViewportView(FactureTable);

        TotalLabel.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        TotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalLabel.setText("TOTAL  :");

        TotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalFieldActionPerformed(evt);
            }
        });

        FactureName.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N
        FactureName.setForeground(new java.awt.Color(255, 255, 255));
        FactureName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FactureName.setText("FACTURE");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        NpLabel.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        NpLabel.setForeground(new java.awt.Color(255, 255, 255));
        NpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NpLabel.setText("NET A PAYER (Tva = 500F):");

        NpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NpFieldActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        jButton3.setText("ANNULER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        jButton2.setText("VALIDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ImpressionBtn.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        ImpressionBtn.setText("IMPRIMER ");
        ImpressionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpressionBtnActionPerformed(evt);
            }
        });

        jScrollPane3.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        ProduitsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Designation", "Quantité", "Prix Unitaire"
            }
        ));
        ProduitsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProduitsTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ProduitsTable);

        SearchBtn.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        SearchBar.setFont(new java.awt.Font("AR CENA", 0, 12)); // NOI18N
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        SearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchBarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout VentesTabLayout = new javax.swing.GroupLayout(VentesTab);
        VentesTab.setLayout(VentesTabLayout);
        VentesTabLayout.setHorizontalGroup(
            VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentesTabLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(VentesTabLayout.createSequentialGroup()
                        .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChoixProduitTabVente2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(VentesTabLayout.createSequentialGroup()
                                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentesTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FactureName, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentesTabLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VentesTabLayout.createSequentialGroup()
                                .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NpField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(VentesTabLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ImpressionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))))
                    .addGroup(VentesTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FactureScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        VentesTabLayout.setVerticalGroup(
            VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentesTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChoixProduitTabVente2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentesTabLayout.createSequentialGroup()
                        .addComponent(FactureName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FactureScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NpField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImpressionBtn)
                            .addComponent(jButton3)
                            .addComponent(jButton2)))
                    .addGroup(VentesTabLayout.createSequentialGroup()
                        .addGroup(VentesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentesTab, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentesTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("VENTE", jPanel2);

        jMenuBar1.setBackground(java.awt.SystemColor.activeCaption);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Fichier");
        jMenu1.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N

        jMenuItem1.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem1.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("Deconnexion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem2.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setBackground(java.awt.SystemColor.activeCaption);
        jMenuItem3.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setText("Aide");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("AR CENA", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "NOT YET AVAILABLE!!!");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aurevoir et à la prochaine ✨👌🚗💨!!!");
        LoginFrame Logout = new LoginFrame();
         Logout.setVisible(true);
         this.setVisible(false); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void DateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DateLabelMouseClicked

    private void FactureTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FactureTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) FactureTable.getModel();
        int row = ProduitsTable.rowAtPoint(evt.getPoint());
        int col = ProduitsTable.columnAtPoint(evt.getPoint());
        int selectedrowindex = FactureTable.getSelectedRow();
        if (row >=0 && col>=0){
            int z = 0;
            z = Integer.valueOf(JOptionPane.showInputDialog("Quantité"));
            if (z>0){
                model.setValueAt(z,selectedrowindex,2);
            }
            int net = 0, total =0, tva= 0;
            for (int i=0; i<FactureTable.getRowCount();i++){
                total += (int) model.getValueAt(i,2)* Double.valueOf((String)model.getValueAt(i, 3));
            }
            net += total + tva;
            TotalField.setText(total + " XAF");
            NpField.setText(net + " XAF");
        }
    }//GEN-LAST:event_FactureTableMouseClicked

    private void TotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalFieldActionPerformed

    private void NpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NpFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) FactureTable.getModel();

        for (int i=0; i<FactureTable.getRowCount(); i++){
            model.removeRow(i);
        }
        TotalField.setText("");
        NpField.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ImpressionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpressionBtnActionPerformed
        // TODO add your handling code here:
        try{
            MessageFormat header = new MessageFormat("Facture");
            MessageFormat footer = new MessageFormat("Page(0, number, integer)");
            FactureTable.print(JTable.PrintMode.NORMAL, header, footer);
            TotalField.print();
            NpField.print();
        }catch (PrinterException ex){
            Logger.getLogger(VenteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ImpressionBtnActionPerformed

    private void ProduitsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProduitsTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ProduitsTable.getModel();
        DefaultTableModel mode = (DefaultTableModel) FactureTable.getModel();
        int row = ProduitsTable.rowAtPoint(evt.getPoint());
        int col = ProduitsTable.columnAtPoint(evt.getPoint());
        if (row >=0 && col>=0){
            // JOptionPane.showMessageDialog(null, "Code : "+ model.getValueAt(row,0) + " Désignation:  " +model.getValueAt(row, 1) + " Quantité : " +model.getValueAt(row, 2)+ " Prix unitaire : " + model.getValueAt(row, 3)+ "Francs CFA "); //ici on affiche les valeurs du tableau cliqué
            int y = 0;
            y = Integer.valueOf(JOptionPane.showInputDialog("Quantité"));
            if (y>0){
                dataFact = new Object[] {
                    model.getValueAt(row, 0),
                    model.getValueAt(row, 1),
                    y,
                    model.getValueAt(row, 3),
                };
                mode.addRow(dataFact);
            }
            else{
                JOptionPane.showMessageDialog(null, "Entrez une valeur valide");
            }
            int net = 0, total =0, tva= 500;
            for (int i=0; i<FactureTable.getRowCount();i++){
                total += (int) mode.getValueAt(i,2)* Double.valueOf((String)mode.getValueAt(i, 3));
            }
            net += total + tva;
            TotalField.setText(total + " XAF");
            NpField.setText(net + " XAF");
        }
    }//GEN-LAST:event_ProduitsTableMouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // Actions à effectuer sur le searchbar
        //  JOptionPane.showMessageDialog(null, SearchBar.getText());
        Recherche();
        // Ici les valeurs dun tableau sont dans le TableModel
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void SearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchBarKeyReleased
        // TODO add your handling code here:
        Recherche();
    }//GEN-LAST:event_SearchBarKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
               DefaultTableModel model = (DefaultTableModel) FactureTable.getModel();
       model.addRow(new Object []{"TOTAL", null, null, TotalField.getText()});
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vente2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vente2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vente2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vente2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vente2Frame().setVisible(true);
            }
        });
    }
    
                  public void Recherche(){
            DefaultTableModel model = (DefaultTableModel) ProduitsTable.getModel();
            model.setRowCount(0);
            Statement stmt = DB.getStatement();
            String sql = "select * from produit  where produit.designation like '%" +SearchBar.getText()+"%' order by id_produit";
            try{
            ResultSet rs = stmt.executeQuery(sql);
             while (rs.next()){
                String code = rs.getString("code_produit");
                String designation = rs.getString("designation");
                Double prix = rs.getDouble("prix");
                int qte = rs.getInt("qte_stock");
                Date date = rs.getDate("date_peremption");
                model.addRow( new Object[]{code,designation,String.valueOf(qte),String.valueOf(prix),String.valueOf(date)}); 
              }
              repaint();
            }catch (Exception exp){
                exp.printStackTrace();
              }
          }
                  
                                            public void RemplirTableauProduit(){
            DefaultTableModel model = (DefaultTableModel) ProduitsTable.getModel();
            model.setRowCount(0);
            try{
            Statement stmt = DB.getStatement();
            String sql = "select * from produit ORDER BY id_produit";
            ResultSet rs = stmt.executeQuery(sql);
              while (rs.next()){
                String code = rs.getString("code_produit");
                String designation = rs.getString("designation");
                Double prix = rs.getDouble("prix");
                int qte = rs.getInt("qte_stock");
                Date date = rs.getDate("date_peremption");
                model.addRow( new Object[]{code,designation,String.valueOf(qte),String.valueOf(prix),String.valueOf(date)});
              }
              repaint();
            }catch (Exception exp){
                exp.printStackTrace();
              }
          }
     Thread clock;
    private Object[] dataFact;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChoixProduitTabVente2;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel FactureName;
    private javax.swing.JScrollPane FactureScroll1;
    private javax.swing.JTable FactureTable;
    private javax.swing.JButton ImpressionBtn;
    private javax.swing.JTextField NpField;
    private javax.swing.JLabel NpLabel;
    private javax.swing.JTable ProduitsTable;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField TotalField;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JPanel VentesTab;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
